.. _ref::AMPLException:

AMPLException
-------------

.. autoclass:: amplpy.AMPLException
  :member-order: bysource
  :members:
  :undoc-members:
  :special-members:
